/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "MEEEEI",
	author = "ME",
	description = "sasha_loh",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	
}
