/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Who_is_thot",
	author = "PiLoGuN",
	description = "Did your a thot maybe yes",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	public CreateConVar()
}
